name: mine_com_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  fl_chart: ^0.68.0
  flutter_riverpod: ^2.4.0
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.0.0
  dartssh2: ^2.13.0
  xterm: ^4.0.0
  postgres: ^3.5.8
  web_socket_channel: ^3.0.3
  http: ^1.2.0
  flutter_local_notifications: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_annotation: ^2.3.3
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.7


flutter:
  uses-material-design: true
  generate: true
